version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.3.0
        steps:
            - checkout
            - restore_cache:
                name: Restore npm Package Cache
                keys:
                    - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
                    - npm-packages-{{ .Branch }}
                    - npm-packages-master
                    - npm-packages-
            - run:
                name: Install Dependencies
                command: npm ci
            - save_cache:
                name: Save npm Package Cache
                key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules/
            - run:
                name: Run Static Analysis Test
                command: npm run lint
            - run:
                name: Run Unit Tests and Build
                command: npm run build
            - store_test_results:
                path: ./build/reports/test
            - store_artifacts:
                path: ./build/reports/coverage
                destination: coverage-report
            - store_artifacts:
                path: ./build/reports/test
                destination: unit-test-report
workflows:
    version: 2
    test_and_build:
        jobs:
            - build  
